# -*- coding: utf-8 -*-

from . import models
from . import servicio
from . import categoria_nomenclador
from . import poblacion_asistida
from . import nomenclador
from . import nomenclador_costo
from . import cliente
from . import paciente
from . import diagnostico
from . import prestador
from . import efector
from . import tecnico
from . import vigencia
from . import vigencia_costo
from . import vigencia_costo_nomenclador
from . import zona_geografica
from . import zona_cobertura
from . import zona_costos
from . import feriados
from . import res_bank_extended
from . import equipamiento
from . import plan_trabajo
from . import agenda
from . import visit
from . import profesion
from . import plan_trabajo_line
from . import plan_trabajo_line_original
from . import sale_order
from . import sale_order_line
from . import hr_applicant_extend
from . import hr_expense_extended
from . import hr_expense_sheet_extended
from . import dias_semana
from . import nodo
from . import internaciones
from . import convenio
from . import modelo_pami
from . import visitas_pami
from . import modulado
from . import modulado_line
from . import prestacion_pami
from . import excepcion_costo_prestador